version: "3.5"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    restart: always
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - 9870:9870
      - 9000:9000
    networks: 
      - hive_default
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    restart: always
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    # ports:
    #   - "50075:50075"
    networks: 
      - hive_default

  hive-server:
    image: bde2020/hive:3.1.2-postgresql-metastore
    restart: always
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hivemetastore:9083"
    ports:
      - "10000:10000"
    networks: 
      - hive_default

  hivemetastore:
    image: bde2020/hive:3.1.2-postgresql-metastore
    restart: always
    container_name: hivemeastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    networks: 
      - hive_default


  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:3.1.0
    networks: 
      - hive_default
    
  presto-coordinator:
    image: prestosql/presto:329
    ports:
      - "8080:8080"
    networks: 
      - hive_default
    

volumes:
  namenode:
  datanode:

networks: 
  hive_default:
    name: hive